version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - '${CHROMA_PORT:-8001}:8000'
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=*
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/v1/heartbeat']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app:
    build: .
    ports:
      - '${APP_PORT:-3001}:3001'
    environment:
      - CHROMA_DB_URL=http://chromadb:8000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      chromadb:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  chromadb_data:
